languageCode = "en-us"
baseURL = "//chanin.tech/"
title = "Mohit Manoj"
paginate = 5
theme = "PaperMod"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "MohitManoj"
description = "TI'm **Mohit Manoj** and this is my Portfolio website."
keywords = [ "Blog", "Portfolio", "Development" ]
author = "Mohit Manoj"
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

  [params.label]
  text = "Mohit Manoj"
  icon = "images/coding.png"
  iconHeight = 35

  [params.profileMode]
  enabled = true
  title = "Hi There! 👋"
  subtitle = "I'm **Mohit Manoj** and this is my Portfolio website."
  imageUrl = "images/pfp.png"
  imageWidth = 120
  imageHeight = 120
  imageTitle = "Me"





  [params.homeInfoParams]
  Title = "Hi There! 👋"
  Content = "I'm **Mohit Manoj** and this is my Portfolio website."

 [[params.socialIcons]]
 name = "instagram"
 url = "https://www.instagram.com/mohit_manoj_/"

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/mohit-manoj-10b364204/"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/lolzone13"



[params.analytics.google]
SiteVerificationTag = "XYZabc"

[params.analytics.bing]
SiteVerificationTag = "XYZabc"

[params.analytics.yandex]
SiteVerificationTag = "XYZabc"

  [params.cover]
  hidden = true
  hiddenInList = true
  hiddenInSingle = false

  [params.editPost]
  URL = ""
  Text = ""
  appendFilePath = true

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 3

[[menu.main]]
identifier = "blog"
name = "Blogs"
url = "/blogs/"
weight = 2

[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects/"
weight = 1

